[book]
authors = ["Carson Katri"]
language = "en"
multilingual = false
src = "src"
title = "Geometry Script"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
additional-css = ["style.css"]